### ISSUE TITLE
support InfluxDB 1.0

### ISSUE THREAD

**Issue by dvdjaco** [n1tr0g/golja-influxdb#46]
InfluxDB 1.0 was officially released today. Looking at the release notes the only relevant changes seem to be in the config file, any plans about it?

**Comment by dnsmichi** [comment]
Using the default class, the influxd daemon cannot be started. 

```
Sep  8 19:00:55 centos-7 influxd: [run] 2016/09/08 19:00:55 Using configuration at: /etc/influxdb/influxdb.conf
Sep  8 19:00:55 centos-7 influxd: run: parse config: toml: cannot load TOML value of type map[string]interface {} into a Go slice
```

Applying the config changes from the [changelog](https://raw.githubusercontent.com/influxdb/influxdb/master/CHANGELOG.md), it will work. 

- data-logging-enabled -> trace-logging-enabled
- [cluster] -> [coordinator]

These are the slice errors:

- [collectd] -> [[collectd]]
- [opentsdb] -> [[opentsdb]]

I'll prepare a PR, I'm using your great module inside the icinga2x-influxdb Vagrant box :)

**Comment by dnsmichi** [comment]
PR #47 - for tests:

`git clone https://github.com/Icinga/icinga-vagrant && cd icinga-vagrant/icinga2x-influxdb && vagrant up`

**Comment by n1tr0g** [comment]
i will review the changes in the next days and release the new version fully supporting v1.0

**Comment by codec** [comment]
You might also be interested in https://github.com/codec/golja-influxdb/commit/6d62ed56de6714a9f17ea19516b46ac1d66ceed6 (I'm not sending a PR for this because I've branched off of @dnsmichi's changes)

**Comment by KlavsKlavsen** [comment]
looking forward to module supporting 1.0 - so I can start with the first influxdb GA in my new install :)

**Comment by mrh666** [comment]
+1 can't wait to test v.1.0! :)

**Comment by n1tr0g** [comment]
the module is officially released.
