### ISSUE TITLE
UDP not configurable

### ISSUE THREAD

**Issue by nohn** [n1tr0g/golja-influxdb#8]
To reproduce:

    class { "influxdb::server":
        udp_enabled => true,
        udp_database => "helios",
        udp_bind_address => ":8089",
    }

expected result:

    [[udp]]
      enabled = true
      bind-address = ":8089"
      database = "helios"

actual result

    [udp]
      enabled = true
      bind-address = ":8089"
      database = "helios"

this leads to influxdb 0.9.3 not starting:

    run: parse config: Type mismatch for 'run.Config.udp': Expected slice but found 'map[string]interface {}'.

**Comment by n1tr0g** [comment]
tnx probably the template is wrong .... Do you want to create an PR or do you want me to fix it ?

**Comment by nohn** [comment]
Done. See https://github.com/n1tr0g/golja-influxdb/pull/9
